### ISSUE TITLE
Add Support for Nested Solutions

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs-wiki-generator#18]
We're currently planning to start nesting our solutions in folders, so each solution can have multiple alternatives. As a result, this tool will need to be updated to support the change.

**Comment by Alcha** [comment]
So instead of the repository having a bunch of folders with the first letter they now will be sorted by the problems?

**Comment by jrg94** [comment]
Not exactly. Someone submitted an alternative solution to Fibonacci in Rudy, and we were debating how to handle that. Ultimately, we decided to add another layer to the repo to support alternative solutions: archive/r/rust/fibonacci/fibonacci-dynamic.rs

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jrg94** [comment]
I don't think we're actually going to implement the nesting. It's already a nightmare as-is.
