### ISSUE TITLE
Add Script Totals to Languages in Wiki

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs-wiki-generator#5]
To aid in some of the analytics of this repo, I'd like to start tracking the number of scripts per language and total them in their respective tables. Then, we can transfer that data to the master tables.

Did I mention I love data?

**Comment by Alcha** [comment]
Would all of this be done within the `Wiki-Generator.py` script you wrote a few days back?

**Comment by Alcha** [comment]
Awesome! I'm still tinkering with the Typescript GitHub App that could do this for us as well so if anything we could possibly replace the script with this whenever I get it complete 😅
